apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart-mongodb.fullname" . }}
  labels:
    {{- include "cart-mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
  selector:
    {{- include "cart-mongodb.selectorLabels" . | nindent 4 }}
