apiVersion: v2
name: crm-mongodb
version: 1.0.0
description: Helm chart for MongoDB database for CRM microservice
type: application
appVersion: "7.0"
maintainers:
  - name: DevOps Team
    email: devops@capstone.com
keywords:
  - mongodb
  - database
  - crm
  - microservice
home: https://github.com/nagendra-sathyamurthy/capstone
sources:
  - https://github.com/nagendra-sathyamurthy/capstone