apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: authentication-mongodb
  template:
    metadata:
      labels:
        app: authentication-mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodbUser }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodbPassword }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodbDatabase }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
