apiVersion: v1
kind: Service
metadata:
  name: catalog-mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
  selector:
    app: catalog-mongodb
