apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-mongodb.fullname" . }}
  labels:
    {{- include "order-mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "order-mongodb.selectorLabels" . | nindent 4 }}